version: '3.3'
services:
  mailtrap:
    image: eaudeweb/mailtrap
    platform: linux/amd64
    ports:
      - 9082:80
      - "127.0.0.1:${SMTP_PORT}:25"
    networks:
      - webnet
  adminer:
    image: adminer:latest
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - webnet
  redis:
    image: redis:5
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - webnet
  postgres:
    image: postgres:11
    volumes:
      - data-volume:/data/db
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - webnet
networks:
  webnet:
volumes:
  data-volume: